src/HR/AppBundle/Entity/Product.php
<?php

namespace HR\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Product
 *
 * @ORM\Table(name="products")
 * @ORM\Entity(repositoryClass="HR\AppBundle\Repository\ProductRepository")
 */
class Product
{
    const LIMIT = 8;
    public static $genderNames = [
        0 => 'Both',
        1 => 'Man',
        2 => 'Women'
    ];

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string")
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;

    /**
     * @var integer
     *
     * @ORM\Column(name="gender", type="integer")
     */
    private $gender;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_accessory", type="boolean")
     */
    private $isAccessory;

    /**
     * @var integer
     *
     * @ORM\Column(name="discount", type="integer")
     */
    private $discount;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", nullable=true)
     */
    private $image;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Product
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set price
     *
     * @param integer $price
     *
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return integer
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set gender
     *
     * @param integer $gender
     *
     * @return Product
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return integer
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set discount
     *
     * @param integer $discount
     *
     * @return Product
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * Get discount
     *
     * @return integer
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    public function calcDiscount()
    {
        return $this->price * $this->discount / 100;
    }

    public function getDiscountPrice()
    {
        return $this->price - $this->calcDiscount();
    }

    /**
     * Set isAccessory
     *
     * @param boolean $isAccessory
     *
     * @return Product
     */
    public function setIsAccessory($isAccessory)
    {
        $this->isAccessory = $isAccessory;

        return $this;
    }

    /**
     * Get isAccessory
     *
     * @return boolean
     */
    public function getIsAccessory()
    {
        return $this->isAccessory;
    }

    public function __toString()
    {
        return $this->getTitle() ? $this->getTitle() : '';
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return Product
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    public function getTemplateDir(){
        return '/uploads/products/'.$this->getId();
    }
    public function getImageUrl(){
        return $this->getTemplateDir().'/'.$this->getImage();
    }

    public function getGenderName(){
        return static::$genderNames[$this->gender];
    }
}

src/HR/AppBundle/Entity/Slides.php
<?php

namespace HR\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Slides
 *
 * @ORM\Table(name="slides")
 * @ORM\Entity(repositoryClass="HR\AppBundle\Repository\SlidesRepository")
 */
class Slides
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="subtitle", type="string", length=255, nullable=true)
     */
    private $subtitle;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     */
    private $url;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Slides
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set subtitle
     *
     * @param string $subtitle
     *
     * @return Slides
     */
    public function setSubtitle($subtitle)
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    /**
     * Get subtitle
     *
     * @return string
     */
    public function getSubtitle()
    {
        return $this->subtitle;
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return Slides
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Slides
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }
    public function getTemplateDir(){
        return '/uploads/slider/'.$this->getId();
    }
    public function getImageUrl(){
        return $this->getTemplateDir().'/'.$this->getImage();
    }

    public function getGenderName(){
        return static::$genderNames[$this->gender];
    }
}

src/HR/AppBundle/Controller/CheckoutController.php
<?php

namespace HR\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use HR\AppBundle\Form\OrderType;
use HR\AppBundle\Entity\Order;

class CheckoutController extends Controller
{
    public function indexAction(Request $request){
        $user = $this->getUser();
        $userId = $user ? $user->getId() : null;
        $userToken = $request->cookies->get('user-token'); # get userToken

        $products = $this->getDoctrine()->getRepository('HRAppBundle:Cart')->getProducts($userId, $userToken);
        if(!$products){
        	return $this->redirectToRoute('homepage');
        }
        return $this->render('HRAppBundle:Checkout:index.html.twig', [
        		'products' => $products
        	]);
    }
    public function readyAction(Request $request){

        $user = $this->getUser();

        $userId = $user ? $user->getId() : null;
        $userToken = $request->cookies->get('user-token'); # get userToken

        $carts = $this->getDoctrine()->getRepository('HRAppBundle:Cart')->findBy(['user' => $userId]);

        $form = $this->createForm(OrderType::class, new Order());

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {



            $order = $form->getData();
            $order->setUser($user);

            $em = $this->getDoctrine()->getManager();
            $em->persist($order);
            $em->flush();

            $inserts = [];
            foreach($carts as $c){
                $p = $c->getProduct();
                $inserts[] = [
                    'order_id' => $order->getId(),
                    'product_id' => $p->getId(),
                    'product_title' => $p->getTitle(),
                    'product_price' => $p->getDiscountPrice(),
                    'product_quantity' => $c->getQuantity(),
                ];
            }
            $this->getDoctrine()->getRepository('HRAppBundle:OrderProduct')->multiInsert($inserts);
            $this->getDoctrine()->getRepository('HRAppBundle:Cart')->deleteCartByUser($userId);

            # Setup the message
            $message = \Swift_Message::newInstance()
                ->setSubject('Order test')
                ->setFrom('0984326650maxim@gmail.com')
                ->setTo($order->getEmail())
                ->setBody($this->get('templating')->render('mail/order.html.twig', ['order' => $order]), 'text/html');

            # Setup the message
            $messageToManager = \Swift_Message::newInstance()
                ->setSubject('Order test')
                ->setFrom('0984326650maxim@gmail.com')
                ->setTo($this->getParameter('manager_email'))
                ->setBody($this->get('templating')->render('mail/order.html.twig', ['order' => $order]), 'text/html');

            
            $sent = $this->get('mailer')
                ->send($message);

            $this->get('mailer')->send($messageToManager);

            $this->addFlash(
                'thankyou',
                "Thank you for your order! Order number #".$order->getId()
            );

            return $this->redirectToRoute('checkout_thankyou');
            //echo $order->getEmail();


        }
        if(!$carts){
            return $this->redirectToRoute('homepage');
        }
        return $this->render('HRAppBundle:Checkout:ready.html.twig', [
                'products' => $carts,
                'form' => $form->createView()
            ]);
    }

    public function thankyouAction(Request $request){
            $session = $this->get('session');
            $checkMessage = $session->getFlashBag()->has('thankyou');
            if(!$checkMessage){
                return $this->redirectToRoute('homepage');
            }
            return $this->render('HRAppBundle:Checkout:thankyou.html.twig');
    }
}

src/HR/AppBundle/Resources/views/Checkout/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% set total = 0 %}
 <main id="main">
      <!-- main-column begin -->
    <article id="main-column">
        <div class="container">

             <!-- begin breadcrumbs -->
          <section class="breadcrumbs">
            <div class="container">
              <ul class="breadcrumb">
                <li><a href="#">Home</a></li>

                <li>/</li>
                <li class="active">Shopping cart</li>
              </ul>
            </div>
          </section>
          <!-- end breadcrumbs -->



            <!-- begin shoping-cart -->
          <section class="shopping-cart">
            <div class="section-head">
              <h2>Shopping cart</h2>
              <div class="dev-line"></div>
            </div>
            <table class="cart-list" id="cart-list">
                <thead>
                  <tr>
                    <th>Product photo</th>
                    <th>Product name</th>
                    <th>description</th>
                    <th>price</th>
                    <th>quantity</th>
                    <th>total price</th>
                  </tr>
                </thead>

                <tbody>
                  {% for cart in products %}
                  {% set product = cart.product %}
                  <tr data-cart-id="{{cart.id}}" data-product-id="{{product.id}}" class="checkout-product">
                    <td>
                      <div class="product-photo">
                        <img src="{{ product.imageUrl }}" alt="photo">
                      </div>
                    </td>

                    <td>
                      <div class="product-name">
                        {{ product.title }}
                      </div>
                    </td>

                    <td>
                      <div class="product-desription">
                        {{ product.description }}
                      </div>
                    </td>

                    <td>
                      <div class="product-price" data-price="{{ product.discountPrice }}">
                        $ {{ product.discountPrice }}
                      </div>
                    </td>

                    <td>
                      <div class="product-quantity checkout-quantity">
                        <input type="text" name="quantity1" class="quantity checkout-quantity" value="{{cart.quantity}}">
                        <span class="plus checkout-quantity-modify" data-modify="+1"><i class="fa fa-angle-up" aria-hidden="true"></i></span>
                        <span data-modify="-1" class="minus checkout-quantity-modify"><i class="fa fa-angle-down" aria-hidden="true"></i></span>

                      </div>
                    </td>

                    <td>
                      <div class="product-total-price">
                          $ {{cart.quantity*product.discountPrice}}
                      </div>
                    </td>
                    <td>
                      <div class="actions">
                        <button class="remove-item checkout-delete"><i class="fa fa-times" aria-hidden="true"></i></button>
                      </div>
                    </td>
                  </tr>
                  {% set total = total + cart.quantity*product.discountPrice %}
                  {% endfor %}
                </tbody>
            </table>


            <div class="total-price-products">
              <div class="section-head">
                <h2>cart totals</h2>
                <div class="dev-line"></div>
              </div>

              <div class="item clearfix">
                <div class="label">Cart Totals</div>
                <div id="all-total">$ {{total}}</div>
              </div>
            </div>


            <div class="cart-actions">
              <a href="{{url('checkout_ready') }}">
              <button class="btn btn-proceed-checkout">Proceed to checkout</button>
              </a>
            </div>
          </section>
           <!-- end shoping-cart -->

      </div>
    </article>
          <!-- main-column end -->
 </main>
{% endblock %}

src/HR/AppBundle/Resources/views/Checkout/ready.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% set total = 0 %}
 <main id="main" class="login">
    <article id="main-column">
    <div class="container">
        <div class="login-center">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            <input type="submit" value="Submit"/>
            {{ form_end(form) }}
        </div>
    </div>
    </article>
 </main>

{% endblock %}

src/HR/AppBundle/Resources/views/Checkout/thankyou.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<main id="main">
    <article id="main-column">
        <div class="container">
        {% for flash_message in app.session.flashBag.get('thankyou') %}
            <div class="flash-notice">
                {{ flash_message }}
            </div>
        {% endfor %}
        </div>
    </article>
 </main>


{% endblock %}